### ISSUE TITLE
dataset.remote_access(use_xarray=True)

### ISSUE THREAD

**Issue by spurpuraUNCC** [Unidata/siphon#314] opened 2021-01-11 20:19 UTC
Trying to follow this tutorial to plot satellite data: https://unidata.github.io/python-training/workshop/Satellite_Data/plotting-satellite-data/

I am able to siphon in the data, but when I use xarray, I am getting an error. 

```python
ds = dataset.remote_access(use_xarray=True)
 
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-12-a599b1a828e9> in <module>
----> 1 ds = dataset.remote_access(use_xarray=True)

~/opt/anaconda3/lib/python3.7/site-packages/siphon/catalog.py in remote_access(self, service, use_xarray)
    620             raise ValueError(service + ' is not a valid service for remote_access')
    621 
--> 622         return self.access_with_service(service, use_xarray)
    623 
    624     def subset(self, service=None):

~/opt/anaconda3/lib/python3.7/site-packages/siphon/catalog.py in access_with_service(self, service, use_xarray)
    672         if service == 'CdmRemote':
    673             if use_xarray:
--> 674                 from .cdmr.xarray_support import CDMRemoteStore
    675                 try:
    676                     import xarray as xr

~/opt/anaconda3/lib/python3.7/site-packages/siphon/cdmr/xarray_support.py in <module>
      7 from xarray.backends.common import AbstractDataStore, BackendArray
      8 from xarray.core import indexing
----> 9 from xarray.core.utils import FrozenOrderedDict
     10 
     11 from . import Dataset

ImportError: cannot import name 'FrozenOrderedDict' from 'xarray.core.utils' (/Users/sarahpurpura/opt/anaconda3/lib/python3.7/site-packages/xarray/core/utils.py)
```

**Comment by RemiSahl** [comment] 2021-03-01 16:18
This is the same problem mentioned in: https://github.com/Unidata/siphon/issues/312

I am also having the issue. Has anyone found a workaround for this while we wait for 0.9 ?

**Comment by dopplershift** [comment] 2021-03-06 03:44
Closing as duplicate of #312. 0.9 should be released shortly.

**Closed by dopplershift** 2021-03-06 03:44 UTC
Labels: Area: Catalog, Status: Duplicate, Type: Bug
