### ISSUE TITLE
Move iastate upper air from MetPy

### ISSUE THREAD

**Issue by jrleeman** [Unidata/siphon#190] opened 2018-03-01 14:53 UTC
The upper air data support in MetPy goes away in the upcoming release (0.8) and we need to have the Iowa archive code moved here before then so folks can continue to use it.

**Comment by dopplershift** [comment] 2018-03-01 17:04
Duplicate of #156 .

**Closed by dopplershift** 2018-03-01 17:04 UTC
Labels: Area: Web Services

**Comment by jrleeman** [comment] 2018-03-01 17:07
Ha - I searched for this and Iowa doesn't return anything... Yay for filing more verbose issues so we can find them I suppose.
