### ISSUE TITLE
conda package incompatible with Python 3.5

### ISSUE THREAD

**Issue by wholmgren** [Unidata/siphon#84] opened 2016-01-14 21:17 UTC
Conda says that siphon and Python 3.5 are in conflict with each other on both linux and mac. It looks like you have 3.5 binaries on [anaconda.org](https://anaconda.org/Unidata/siphon/files), so maybe something specific to how you built them?

```
(root)holmgren-mbp:sphinx holmgren$ conda create --name siphon python=3.5
Fetching package metadata: ....
Solving package specifications: ..........
Package plan for installation in environment /Users/holmgren/miniconda3/envs/siphon:

The following NEW packages will be INSTALLED:

    openssl:    1.0.2e-0
    pip:        7.1.2-py35_0
    python:     3.5.1-0
    readline:   6.2-2
    setuptools: 19.1.1-py35_0
    sqlite:     3.9.2-0
    tk:         8.5.18-0
    wheel:      0.26.0-py35_1
    xz:         5.0.5-0
    zlib:       1.2.8-0

Proceed ([y]/n)? y

Linking packages ...
[      COMPLETE      ]|#################################################################################################################################################################################################################| 100%
#
# To activate this environment, use:
# $ source activate siphon
#
# To deactivate this environment, use:
# $ source deactivate
#
(root)holmgren-mbp:sphinx holmgren$ source activate siphon
discarding /Users/holmgren/miniconda3/bin from PATH
prepending /Users/holmgren/miniconda3/envs/siphon/bin to PATH
(siphon)holmgren-mbp:sphinx holmgren$ conda install -c Unidata siphon
Fetching package metadata: ......
Solving package specifications: ...........
Error: Unsatisfiable package specifications.
Generating hint:
[      COMPLETE      ]|#################################################################################################################################################################################################################| 100%


Hint: the following packages conflict with each other:
  - siphon
  - python 3.5*

Use 'conda info siphon' etc. to see the dependencies for each package.
```

**Comment by dopplershift** [comment] 2016-01-16 20:35
I think this has something to do with building the package for 3.5, but missing a dependency for it on 3.5 (which is caused by things going wrong on our unidata/conda-recipes repo automatically building).

I'm tempted to pull the 3.5 package until I fix it. How important is 3.5 for you? (To be clear, I myself am using 3.5 on a daily basis, just not our own conda packages).

**Comment by wholmgren** [comment] 2016-01-17 18:44
No rush, just letting you know.

**Comment by ocefpaf** [comment] 2016-01-17 21:20
@wholmgren We have the latest siphon for Python 3.5 in the IOOS channel.

Try `conda install -c ioos siphon`  and let us know if that works for you.

**Comment by wholmgren** [comment] 2016-01-17 22:12
@ocefpaf that works, thanks. Did you make your own siphon build to work around this problem? In the long run, I'd prefer to just use Unidata builds for simplicity.

**Comment by ocefpaf** [comment] 2016-01-17 22:33
> Did you make your own siphon build to work around this problem?

Nope.  We ([IOOS channel](https://github.com/ioos/conda-recipes)) maintain a conda channel, akin to Unidata's channel, to help our conda users .

> In the long run, I'd prefer to just use Unidata builds for simplicity

Sure.  I understand that people are more comfortable within their own community. However, we (not IOOS but a larger community of conda users) are currently trying to tackle the package maintenance (and forking) problem. Ideally we should join efforts to maintain high quality conda packages for the whole met/ocean community in one place.

Our solution is [conda-forge](https://github.com/conda-forge).  It is a place where the community can maintain conda recipes, via GitHub (using PRs and Issues), in a very transparent way. The packages are built using CIs services: AppVeyor (Windows), CircleCI (Linux), and Travis-CI (OS X) and are automatically uploaded to the channel when the PR is merged.

I do plan to transfer as much as possible of the IOOS packages to conda-forge and I would love to see the Unidata community there too.

**Comment by dopplershift** [comment] 2016-02-09 19:47
@ocefpaf Giving it a shot with MetPy (which only needs pint as a dependency on top of main packages).

**Comment by ocefpaf** [comment] 2016-02-09 20:03
> @ocefpaf Giving it a shot with MetPy (which only needs pint as a dependency on top of main packages).

I am in the process of moving the package from IOOS to conda-forge.  We can join forces there and send these package.  I saw that you submitted `MetPy`.  Let me send Siphon and you can review the PR :wink:

**Comment by dopplershift** [comment] 2016-02-23 17:16
@wholmgren If you use the [conda-forge](https://anaconda.org/conda-forge/) channel on Anaconda you should be able to get a working set of packages. That's where I'm moving our package builds, so let me know (re-open this) if there's still a problem.

**Closed by dopplershift** 2016-02-23 17:16 UTC
Labels: Area: Infrastructure, Type: Bug

**Comment by wholmgren** [comment] 2016-02-23 22:53
Thanks, your 2.7, 3.4, and 3.5 packages all worked for me.

**Comment by dopplershift** [comment] 2016-02-23 23:28
Great. Thanks for being exhaustive in your testing!
